version: '3.8'

services:
  airflow:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/app/dags
      - ./src:/app/src
      - ./.dlt:/app/.dlt
      - ./logs:/app/airflow/logs
      - ./plugins:/app/plugins
    environment:
      - AIRFLOW_HOME=/app/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/app/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////app/airflow/airflow.db
